import Header from "@/components/header";
import "./globals.css";
import { Cormorant } from "next/font/google";

const cormorant = Cormorant({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${cormorant.className}  h-screen flex flex-col max-h-screen items-stretch`}>
        <Header />
        <div className="flex-grow ">{children}</div>
      </body>
    </html>
  );
}
